@startuml

note "Project: RIA1-FRUSTZ\nTitle: FRUSTZ Class Diagram\nAuthor: SCHNEIDER Julien, DIEPERINK David\nDate: 19/03/25\nVersion: 1.1" as N1

package "Vue" {
    class Index {}
    class Login {}
}

package "Domaine" {

    class Identifier {
            +validateForm(): void
    }
    
    class Translation {
        +i18next: I18Next

        +loadTranslation(lang: String): Promise<any>
        +showError(message: String): void
        +applyTranslations(): void
        +changeLanguage(lang: String): void
    }
    
    class loginAttempt {
        +userIdentifier(loginAttempt : String): String
    }
    
    
    

    class Locale {}
}

package "API" {
    class I18Next {
        +lang: String    
    }
}

package "Exceptions" {
    class LanguageUnknowException {}

    class Error {}
}

' Relations

Index --> Translation : "Call"
Index --> loginAttempt : "Call"
Index - Login
Login --> Translation : "Call"
Login --> Identifier : "Call"
Translation -> I18Next : "Use"
Translation --> Locale : "Load"
LanguageUnknowException -|> Error : "extends"

' Liaison entre API et Exceptions
I18Next --> LanguageUnknowException : "Throw"

@enduml
